Done fixes for different things to make changes into main template
zype/zype-firebuilder pull request #97
Opened 2020-12-01 13:42 UTC by hardikhexa

Done fixes for different things to make changes into main template

2020-12-03 14:14 UTC, ech89899 requested changes
There are too many changes in this single commit to figure out the changes related to the issue in APPS-1476 (Inline title style). Please provide smaller commits, or point which changes are specific for each issue.

2020-12-03 14:14 UTC, ech89899 commented on Application/ZypeAPI/src/main/java/com/zype/fire/api/ZypeSettings.java
> +    public static final String APP_KEY = "_L22X939Nwk6YZde4VvDf8V7iPV15FCYGn-mDI0-1DAznYwYlB1gtsOOZ9lNibCn";
We should not change the app keys for Zype demo build variant

2020-12-03 14:14 UTC, echedev commented on Application/app/build.gradle
> -            applicationId "<APPLICATION_ID>"
We should keep the placeholder for 'template' build variant

2020-12-03 14:14 UTC, ech89899 commented on Application/app/src/template/res/values-de/strings.xml
> +  <string name="app_name">Test app</string>
We should not replace placeholders for 'template' build variant here and in other 'template' files

2020-12-15 05:23 UTC, hardikhexa commented
Hello @ech89899 @mattmoore104 , I missed this and now resolved comments to reverted to placeholders.
please check so we can merge this as soon as possible to master.

2020-12-18 14:07 UTC, merged